### ISSUE TITLE
Use `brew --prefix`'/bin' install path by default

### ISSUE THREAD

**Issue by abitrolly** [whalebrew/whalebrew#273]
What are your arguments against `brew --prefix`'/bin' as a default install path?

Pros: The path already exists and configured to be in PATH when `whalebrew` [is installed with `brew`](https://github.com/whalebrew/whalebrew#install).
Cons: The could be name conflict with `brew` packages.

I would say name conflict probability is low. Need to check what `brew` does if `whalebrew` shim exists. `whalebrew` won't overwrite existing shims https://github.com/whalebrew/whalebrew/blob/e65bf47e714c341e7879ea310383089b17615683/packages/manager.go#L58

**Comment by tjamet** [comment]
Hi!

Most of the pending PRs have been merged and [0.5.0](https://github.com/whalebrew/whalebrew/releases/tag/0.5.0) has been released.
In particular #252 should  fix this issue.

I will close it. Please feel free to re-open it if you still face difficulties

**Comment by abitrolly** [comment]
@tjamet thanks for the heads up. I am actually on Linux, but I am unable to check the new version, because https://github.com/whalebrew/whalebrew/pull/299 prevents Howebrew release.

**Comment by tjamet** [comment]
> @tjamet thanks for the heads up. I am actually on Linux, but I am unable to check the new version, because #299 prevents Howebrew release.

Thanks, this should be fixed now, correct?

**Comment by abitrolly** [comment]
@tjamet well, `whalebrew install whalebrew/whalesay` still doesn't work, now because of https://github.com/whalebrew/whalebrew/issues/301

**Comment by abitrolly** [comment]
With full image URL it works.

The only thing left is `WHALEBREW_INSTALL_PATH` warning, which is not needed anymore.
````sh
$ whalebrew install docker.io/whalebrew/whalesay
Trying to pull docker.io/whalebrew/whalesay:latest...
Getting image source signatures
Copying blob 600c0db384c4 done   | 
Copying blob aa918feae9a0 done   | 
Copying blob 4663f495c836 done   | 
Copying blob c9b1b535fdd9 done   | 
Copying config cc096d29e7 done   | 
Writing manifest to image destination
cc096d29e7db6c1b624cbcd8da74d041a6a3d55f9b716961b69772c192b4e1f6
Installation path is not writable: /usr/local/bin

Set WHALEBREW_INSTALL_PATH environment variable to writable location.
Or set 'install_path` option in '~/.whalebrew/config.yaml`. Make sure
the location is added to PATH. For details, see
https://github.com/whalebrew/whalebrew#configuration

$ whalesay

fsadf
 ________ 
<  fsadf >
 -------- 
    \
     \
      \
                    ##         .
              ## ## ##        ==
           ## ## ## ## ##    ===
       /"""""""""""""""""\___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
       \______ o           __/
         \    \         __/
          \____\_______/
$ which whalesay                                
/home/linuxbrew/.linuxbrew/bin/whalesay
```

**Comment by abitrolly** [comment]
`whalebrew list` doesn't find the newly installed package.

```sh
$ whalebrew list
COMMAND   IMAGE
$ which whalesay       
/home/linuxbrew/.linuxbrew/bin/whalesay
$ cat `which whalesay`
#!/usr/bin/env whalebrew
image: docker.io/whalebrew/whalesay
```

`whalebrew uninstall` doesn't work too.

**Comment by abitrolly** [comment]
@tjamet no, nothing works. The `whalesay` file was too old.

```
$ ls -la `which whalesay`
-rwxr-xr-x. 1 anatoli anatoli 61 Dec 16  2023 /home/linuxbrew/.linuxbrew/bin/whalesay
```

After removing it, `whalesay` doesn't work, and `whalebrew` doesn't see the bin dir.

**Comment by tjamet** [comment]
I see you are using `~/.linuxbrew/bin` as directory for whalebrew files.
This differs from the [default path](https://github.com/whalebrew/whalebrew/pull/252/files#diff-fe44f09c4d5977b5f5eaea29170b6a0748819c9d02271746a20d81a5f3efca17R76), and hence needs either `WHALEBREW_INSTALL_PATH` environment variable to be set, or `install_path` configured in `~/.whalebrew/config.yaml`

I wouldn't install whalebrew in the same bindir as homebrew to avoid conflicts between both packet managers.

I would also avoid any dependency on the homebrew command itself, whalebrew should be self-sufficient and work without needing to install homebrew
